export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      white: '#ffffff',
      black: '#000000',
      primary: {
        50: 'color-mix(in srgb, var(--color-primary), white 85%)',
        100: 'color-mix(in srgb, var(--color-primary), white 75%)',
        200: 'color-mix(in srgb, var(--color-primary), white 60%)',
        300: 'color-mix(in srgb, var(--color-primary), white 45%)',
        400: 'color-mix(in srgb, var(--color-primary), white 30%)',
        500: 'var(--color-primary)',
        600: 'var(--color-primary)',
        700: 'var(--color-primary-700)',
        800: 'var(--color-primary-700)',
        900: 'var(--color-primary-700)',
      },
      secondary: {
        50: 'color-mix(in srgb, var(--color-secondary), white 88%)',
        100: 'color-mix(in srgb, var(--color-secondary), white 78%)',
        200: 'color-mix(in srgb, var(--color-secondary), white 65%)',
        300: 'color-mix(in srgb, var(--color-secondary), white 50%)',
        400: 'color-mix(in srgb, var(--color-secondary), white 35%)',
        500: 'var(--color-secondary)',
        600: 'var(--color-secondary)',
        700: 'color-mix(in srgb, var(--color-secondary), black 20%)',
        800: 'color-mix(in srgb, var(--color-secondary), black 35%)',
        900: 'color-mix(in srgb, var(--color-secondary), black 50%)',
        950: 'color-mix(in srgb, var(--color-secondary), black 60%)',
      },
      accent: {
        50: 'color-mix(in srgb, var(--color-accent), white 85%)',
        100: 'color-mix(in srgb, var(--color-accent), white 75%)',
        200: 'color-mix(in srgb, var(--color-accent), white 60%)',
        300: 'color-mix(in srgb, var(--color-accent), white 45%)',
        400: 'color-mix(in srgb, var(--color-accent), white 30%)',
        500: 'var(--color-accent)',
        600: 'color-mix(in srgb, var(--color-accent), black 15%)',
        700: 'color-mix(in srgb, var(--color-accent), black 30%)',
      },
      gray: {
        50: 'var(--color-bg)',
        100: 'var(--color-bg)',
        200: 'var(--color-border)',
        300: 'var(--color-border)',
        400: 'var(--color-muted)',
        500: 'var(--color-muted)',
        600: 'var(--color-text)',
        700: 'var(--color-text)',
        800: 'var(--color-text)',
        900: 'var(--color-text)',
      },
      slate: {
        50: 'var(--color-bg)',
        100: 'var(--color-bg)',
        200: 'var(--color-border)',
        300: 'var(--color-border)',
        400: 'var(--color-muted)',
        500: 'var(--color-muted)',
        600: 'var(--color-text)',
        700: 'var(--color-text)',
        800: 'var(--color-text)',
        900: 'var(--color-text)',
      },
      emerald: {
        400: 'color-mix(in srgb, var(--color-success), white 20%)',
        500: 'var(--color-success)',
        600: 'color-mix(in srgb, var(--color-success), black 15%)',
      },
      green: {
        50: 'color-mix(in srgb, var(--color-success), white 85%)',
        100: 'color-mix(in srgb, var(--color-success), white 75%)',
        600: 'var(--color-success)',
        700: 'color-mix(in srgb, var(--color-success), black 20%)',
      },
      red: {
        200: 'color-mix(in srgb, var(--color-danger), white 65%)',
        300: 'color-mix(in srgb, var(--color-danger), white 50%)',
        400: 'color-mix(in srgb, var(--color-danger), white 35%)',
        500: 'var(--color-danger)',
        600: 'color-mix(in srgb, var(--color-danger), black 15%)',
        700: 'color-mix(in srgb, var(--color-danger), black 25%)',
      },
      yellow: {
        50: 'color-mix(in srgb, var(--color-warning), white 85%)',
        100: 'color-mix(in srgb, var(--color-warning), white 70%)',
        400: 'color-mix(in srgb, var(--color-warning), white 25%)',
        500: 'var(--color-warning)',
        600: 'color-mix(in srgb, var(--color-warning), black 15%)',
        700: 'color-mix(in srgb, var(--color-warning), black 25%)',
      },
      orange: {
        400: 'color-mix(in srgb, var(--color-warning), white 20%)',
        500: 'var(--color-warning)',
      },
      blue: {
        50: 'color-mix(in srgb, var(--color-secondary), white 85%)',
        400: 'color-mix(in srgb, var(--color-secondary), white 30%)',
        500: 'var(--color-secondary)',
        600: 'color-mix(in srgb, var(--color-secondary), black 15%)',
      },
      cyan: {
        400: 'color-mix(in srgb, var(--color-secondary), white 30%)',
        500: 'var(--color-secondary)',
      },
      teal: {
        500: 'var(--color-secondary)',
      },
      purple: {
        400: 'color-mix(in srgb, var(--color-primary), white 30%)',
        500: 'var(--color-primary)',
        600: 'var(--color-primary-700)',
        900: 'var(--color-primary-700)',
      },
      violet: {
        200: 'color-mix(in srgb, var(--color-primary), white 60%)',
        300: 'color-mix(in srgb, var(--color-primary), white 45%)',
        400: 'color-mix(in srgb, var(--color-primary), white 30%)',
        500: 'var(--color-primary)',
        600: 'var(--color-primary-700)',
      },
      pink: {
        50: 'color-mix(in srgb, var(--color-accent), white 85%)',
        300: 'color-mix(in srgb, var(--color-accent), white 45%)',
        400: 'color-mix(in srgb, var(--color-accent), white 30%)',
        500: 'var(--color-accent)',
        600: 'color-mix(in srgb, var(--color-accent), black 15%)',
      },
      rose: {
        400: 'color-mix(in srgb, var(--color-accent), white 30%)',
        500: 'var(--color-accent)',
      },
    },
    extend: {
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in',
        'slide-up': 'slideUp 0.5s ease-out',
        'bounce-slow': 'bounce 2s infinite',
        'pulse-glow': 'pulseGlow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(236, 72, 153, 0.7)' },
          '50%': { boxShadow: '0 0 0 10px rgba(236, 72, 153, 0)' },
        },
      },
    },
  },
  plugins: [],
}
