#!/bin/bash

# BookMySalon - Quick Reference Guide
# This file contains quick commands and information

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         BookMySalon - Complete Setup & Launch Guide           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📌 QUICK START (EASIEST)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Run automated setup:"
echo "  ./setup.sh"
echo ""

echo "📌 MANUAL SETUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Start MySQL:"
echo "   brew services start mysql"
echo ""
echo "2. Create Database:"
echo "   mysql -h localhost -u root -p"
echo "   CREATE DATABASE bookmysalon;"
echo "   EXIT;"
echo ""
echo "3. Start Backend (Terminal 1):"
echo "   cd bookmysalon-app"
echo "   java -jar target/bookmysalon-app-1.0.0.jar"
echo ""
echo "4. Start Frontend (Terminal 2):"
echo "   cd frontend"
echo "   npm install"
echo "   npm run dev"
echo ""

echo "📌 ACCESS POINTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Frontend: http://localhost:5173"
echo "Backend:  http://localhost:8080"
echo "Database: localhost:3306/bookmysalon"
echo ""

echo "📌 TEST ACCOUNT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Email:    john@example.com"
echo "Password: Password@123"
echo "Role:     CUSTOMER"
echo ""

echo "📌 BUILD & REBUILD"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Rebuild Backend:"
echo "  cd bookmysalon-app && mvn clean install -DskipTests"
echo ""
echo "Rebuild Frontend:"
echo "  cd frontend && npm install && npm run build"
echo ""

echo "📌 PROJECT FILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "setup.sh         - Automated start script"
echo "config.json      - Configuration and API reference"
echo "bookmysalon-app  - Backend (Spring Boot)"
echo "frontend         - Frontend (React)"
echo "architecture-images - Architecture diagrams"
echo ""

echo "📌 KEY FILES TO MODIFY"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Backend Config:"
echo "  bookmysalon-app/src/main/resources/application.yml"
echo ""
echo "Frontend Config:"
echo "  frontend/.env.local"
echo ""
echo "API Configuration:"
echo "  frontend/src/config/api.js"
echo ""

echo "📌 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "MySQL not running:"
echo "  brew services start mysql"
echo ""
echo "Port 5173 in use:"
echo "  cd frontend && npm run dev -- --port 3000"
echo ""
echo "Port 8080 in use:"
echo "  java -jar target/bookmysalon-app-1.0.0.jar --server.port=8081"
echo ""
echo "Clear node_modules & reinstall:"
echo "  cd frontend && rm -rf node_modules && npm install"
echo ""
echo "Rebuild backend from scratch:"
echo "  cd bookmysalon-app && mvn clean install -DskipTests"
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                   Ready to Launch!                            ║"
echo "║              Run: ./setup.sh                                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
